### ISSUE TITLE
TLS1.3

### ISSUE THREAD

**Issue by yzcwf** [ptrd/kwik#1]
Can you provide TLS1.3 source code，is different from the implementation in jdk 11？

**Comment by ptrd** [comment]
It is certainly different. Quic requires different, more low level, interface to TLS than JDK does. Quic only uses TLS handshake protocol. I wrote my own implementation of TLS 1.3 handshake protocol. I decided not (yet) to open source it, because (at first) it was just a kind of poc to see if i would be able to implement Quic in Java, not appropriate for sharing. 
Recently i've been working on improving the code and transforming it into a decent, robust implementation. When i'm finished with that, i'll probably open source it too.
I you really need access to it, please contact me personally (by email).

**Comment by remmerw** [comment]
Would be great if the source code TLS1.3 is available. Background
I try to use (or at least try) the library for Android (it requires  the source code to be compiled in java 8, but
the TLS1.3 is java 11) so currently I can not test(debug) it.

**Comment by ptrd** [comment]
Hi @remmerw. I will open source it, but need to do some clean up first (to avoid people are going to use parts that are unfinished). In the mean time, feel free to mail me at peter dot doornbosch at luminis dot eu; if you tell me which version (commit) of Kwik you are using i can send you a zip with the corresponding tls source.

**Comment by ptrd** [comment]
Source for TLS lib can be found here: https://bitbucket.org/pjtr/agent15/src/master/
