### ISSUE TITLE
Publish to Maven?

### ISSUE THREAD

**Issue by FireMasterK** [ptrd/kwik#2]
Could you publish flupke to a maven repository?
I'd like to use it in a gradle project but there are no repositories listed and Jitpack fails to build flupke.

**Comment by ptrd** [comment]
That has no priority for me at this point in time. Maybe later.

I wonder why you cannot just build it and use the jars in your project. Gradle does allow to use local libraries, see https://stackoverflow.com/questions/20700053/how-to-add-local-jar-file-dependency-to-build-gradle-file

Regards
Peter

**Comment by wangpeng1** [comment]
@ptrd  I put the jar package into the android project, but I can't reference the classes inside, but other jar packages are good

**Comment by ptrd** [comment]
@wangpeng1 
- this has nothing to do with publishing to maven
- you seem to ask me to help you with Android, i don't know why. Try Android community.

**Comment by mikedawson** [comment]
Hi,

I was able to build and include the jars using gradle (e.g. implementation fileTree(dir: 'libs', include: ['*.jar']) ). I was then able to run the echo test within my library (as a unit test) fine. To be on the safe side I modified the build.gradle on kwik so that the jar did not automatically collect all dependencies, and added the dependencies from Kwik's build.gradle to my build.gradle (to avoid a potential duplicate class issue).

Having a pure Java implementation of QUIC is a really great thing to have! It would though be far more convenient to use as a library if it was published on maven.

@ptrd I would be happy to contribute a pull request to implement publishing to maven in Gradle. I think the Gradle distribution plugin can be used so there is a build of the kwik jar on its own and a CLI version with all dependencies.

**Comment by ptrd** [comment]
Hi, 

Thanks for your comment. You're right that is about time to publish to maven. Already got a PR for building with maven, still need to figure out if this is the way to go. Already incorporated it for agent15 btw.

**Comment by mikedawson** [comment]
As you already have a working Gradle build, I would have thought it would make more sense to just use the Gradle publishing plugin, no need to switch build systems.

**Comment by ptrd** [comment]
@mikedawson Indeed. So that's what i did. Kwik is available as lib on maven: https://central.sonatype.com/artifact/net.luminis.networking/kwik

**Comment by ptrd** [comment]
https://central.sonatype.com/artifact/tech.kwik/kwik
