### ISSUE TITLE
QUIC proxy

### ISSUE THREAD

**Issue by ElNiak** [ptrd/kwik#56]
Hello, 

I am planning to do a proxy using Kwik. It part of a scientific research where I need to fuzz decrypted connection.

The idea would be:

IUT-QUIC-client <-> Proxy-fuzzer <-> IUT-QUIC-server

Any idea where to start ? I have in mind to do some kind of Proxy connector like the server with also initiate a connection mirror.

Seems good for you ? Any tips ? 

Thanks !

**Comment by ptrd** [comment]
Sorry, i don't get it. "fuzz decrypted connection", what would that mean?

**Comment by ptrd** [comment]
It depends on what this proxy should do. At what level it would operate. Etc.
You are a researcher and teacher, aren't you? So, I expect you know how to ask smart questions. This kind of ping-pong question-answer is leading nowhere. Of course I'm willing to help, but you need to provide a lot more information of what you want to achieve and where your challenges are if you want me to give you a valuable answer.
You can also email me, that might be a more appropriate channel for these type of discussions.

**Comment by ptrd** [comment]
Nice, that helps.

1. What first comes to mind is the question how you would be able to decrypt the encrypted messages, did you already decide on how to solve that? 
The structure of the solution depends on which route you take. If you terminate the QUIC connection in your proxy and setup a new one to the server (mirroring the properties of the first), creating a proxy would be a matter of tying a server and client and let each of them not respond to messages, but pass them through. This would be simply a matter of overriding all process(xxxPacket) methods. It would also require a different implementation of the sender as you wouldn't want (or need) packets to be queued, but such a sender implementation would be much simpler than the one found in Kwik. Note however that this will only work if the fuzzer does not resize (enlarge) the packet to be send, otherwise it might not fit in a datagram.
The other option would be to somehow transport the connection secrets from one of the real peers to the proxy, so the proxy can decrypt and re-encrypt the packets with the original connection secrets. In the case, you won't need a full fledged client to accompany to server part of the proxy, but you do need the receiving (and decrypting) part of the client to capture the messages send back from the real server.
2. No, not really. Kwik is not designed for that kind of thing. But as explained above, I think you can get quite far by providing your own ServerConnection and ClientConnection classes, extending from Kwik's classes.
3. I wouldn't know. Apart from the essential question how to get your hands on the connection secrets, but that is not specific for Kwik, to holds for any proxy that wants to decrypt QUIC traffic.

Hth
Peter

**Comment by ptrd** [comment]
@ElNiak : can I close this issue?

**Comment by ElNiak** [comment]
Hello, yes thanks for your help !
